/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider */

#ifndef _Included_com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider
#define _Included_com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider
 * Method:    getKeychainPassword
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider_getKeychainPassword
  (JNIEnv *, jobject, jstring, jobject, jstring, jstring, jstring);

/*
 * Class:     com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider
 * Method:    setKeychainPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_leapingbytes_almostvpn_util_macosx_KeychainMasterPasswordProvider_setKeychainPassword
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
